server:
  port: 8989
  servlet:
    context-path: /zhong
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/zhong?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
mybatis:
  type-aliases-package: com.baizhi.wsf.entity
  mapper-locations: classpath:com/baizhi/wsf/mapper/*Mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql